name: puffsat_math_env
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - isort
  - jupyter
  - mypy
  - nbdime
  - pandas
  - poliastro
  - pytest
  - python=3.10
  - tabulate
  - types-tabulate
